<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_company_postal_code</name>
   <tag></tag>
   <elementGuidId>fd9ca0db-357d-41e5-a492-82a94e0ededa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCompanyPostalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCompanyPostalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2b3d317-f07c-4a9a-b3cb-14979707badc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>6e92af73-2523-4370-999b-0c6fb79dc27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>275c4bd6-2c48-4c62-b5d1-0a8eec0820c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control error</value>
      <webElementGuid>bc06c781-6185-4ff8-a092-adcb1044d57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCompanyPostalCode</value>
      <webElementGuid>1095b26f-0d6c-4198-b58c-01f7063f5dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_postal_code</value>
      <webElementGuid>4c709b7f-b1d0-40d1-9a60-00d1986bb053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCompanyPostalCode&quot;)</value>
      <webElementGuid>cf564e38-36b9-4f65-919f-ef9f06bc896c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCompanyPostalCode']</value>
      <webElementGuid>51ad893f-7b98-4f2b-ba3b-f360443dfea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div[11]/div/input</value>
      <webElementGuid>007667a2-1d20-4972-80a8-0b91af93645d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>92aeda80-d4b6-4909-b139-e3319d4af3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputCompanyPostalCode' and @name = 'company_postal_code']</value>
      <webElementGuid>709f06b9-91f4-4d39-8d8c-f8bfa13c36db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
