<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trading_name</name>
   <tag></tag>
   <elementGuidId>9ef07424-8e95-4480-bdde-72807dd6a06e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_trading_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_trading_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46efcc24-2733-4cb3-9163-23ca47da2d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>3123f716-de7f-4d1f-8c99-deaabf28e1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50347e75-2829-49f8-aa75-8c973090cd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit</value>
      <webElementGuid>8721cc8e-f4ee-48a4-91c7-7fcb4c14be2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_trading_name</value>
      <webElementGuid>4fd71150-b356-44d7-aa84-e064f75f961c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trading_name</value>
      <webElementGuid>16c261a6-3f6d-490c-ae9e-f0c4aaa0fc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_trading_name&quot;)</value>
      <webElementGuid>4cdde752-bca4-438c-ab59-c51919240206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_trading_name']</value>
      <webElementGuid>405a463c-11b6-46e5-8b0a-99cf6a4e687e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div[3]/div/input</value>
      <webElementGuid>571f0594-98f4-4420-b52a-245e8d89ce6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>f359f8e6-008b-464f-90f6-73861755d342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_trading_name' and @name = 'trading_name']</value>
      <webElementGuid>7199621f-b89f-46c3-a4d0-27a4d3b0de18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
