<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_company_street_no</name>
   <tag></tag>
   <elementGuidId>3466e2f2-f6b9-402b-9a5b-f83d0a7ebb83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCompanyStreetNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCompanyStreetNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caa3eafa-e741-4e53-99fe-e8dda411f8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>0d9f6239-76b7-4419-a2d5-addc54f34ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e15d372d-7726-4bd6-af09-5753df009751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control error</value>
      <webElementGuid>e9c823fc-90ed-42c8-b4e0-2f8c3771b35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCompanyStreetNo</value>
      <webElementGuid>403cffbb-9ebc-42f1-92b5-60c70cfcd3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_street_no</value>
      <webElementGuid>85d38110-0c12-4fa9-b6ad-e943e326255b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCompanyStreetNo&quot;)</value>
      <webElementGuid>753e3502-c55c-444e-9c44-379f3ee4a90c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCompanyStreetNo']</value>
      <webElementGuid>4b4daa70-2acf-4341-9f09-11724456c8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div[8]/div/input</value>
      <webElementGuid>ba9e1915-37de-4150-a18e-e295a1b5b70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>eb29a2d0-1b30-49bd-a956-19aaca6735ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputCompanyStreetNo' and @name = 'company_street_no']</value>
      <webElementGuid>7e868471-a1d7-4bfe-9bd1-068cc5b5655d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
