<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_company_desc</name>
   <tag></tag>
   <elementGuidId>22512595-6ba9-4c0a-a2be-a2f568c16bfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_company_desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input_company_desc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>509e142a-04ce-43f6-8e92-110674100830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>f08f18c5-5b13-47a2-89e3-3c1e72a54ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8d7d8ce5-4559-4e3a-bb24-4b26506d648d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>57f1aff5-0bad-4f94-b15c-2d25d4be8664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit no-resize error</value>
      <webElementGuid>5f8332be-357c-460a-875b-b0f920e35ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_company_desc</value>
      <webElementGuid>bebdb6f7-378b-41ff-bb7e-5eb9daad4934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company_desc</value>
      <webElementGuid>74b8f16b-0a29-415e-b3d4-bfb978ef0558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_company_desc&quot;)</value>
      <webElementGuid>c8e509b7-c46f-4e8e-b7c9-1b1ca4da53b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input_company_desc']</value>
      <webElementGuid>a46883d8-e9d3-4a59-9d40-4cfd70f9109a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div[5]/div/textarea</value>
      <webElementGuid>55574a6d-29e0-482a-a89d-847d85120e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3db12976-5f20-4f6f-9290-3145c65195c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input_company_desc' and @name = 'company_desc']</value>
      <webElementGuid>2b7929ed-f18f-4e3d-bd62-b8cd40224bf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
