<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_signatory_last_name</name>
   <tag></tag>
   <elementGuidId>fe91402c-7db5-4dea-80fc-436055515908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signatory_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatory_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e94e1c2-e3b0-4d5a-8a86-7eae5c88063e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4bcf169-0ac6-41c1-993f-de0b5f329da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatory_last_name</value>
      <webElementGuid>b00fda94-6c73-4398-86be-3bd0e162d55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-grey</value>
      <webElementGuid>c5eb07ac-6752-4102-983f-b8db563bf6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatory_last_name</value>
      <webElementGuid>d34f266f-27f0-4a1d-a608-3dbf1a90619f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>579542f5-6f35-49bf-a3a2-7a5dd8f314ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>85fe5da7-5d30-4514-964e-a84c0c2a6b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>d2c16e6c-7f04-4353-b0c4-bcf85f9bb555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatory_last_name&quot;)</value>
      <webElementGuid>2e28f1ae-0797-43f3-8ef3-b77fe6ef2d35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatory_last_name']</value>
      <webElementGuid>94c4c295-c212-4f3c-8321-a9ffddaf2887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[3]/div[2]/input</value>
      <webElementGuid>095dfce2-f199-49ec-9bdf-cba81fcb4f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>2a9dbffb-90c0-46b1-b267-45e2f761edc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'signatory_last_name' and @id = 'signatory_last_name' and @placeholder = 'Last name']</value>
      <webElementGuid>c79803ce-5861-4f8d-9f7a-2147f4f12be6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
